application: roguehacklab
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/.*

- url: /(.*)\.(html|js|css|png|ico|txt|jpg)
  static_files: static/\1.\2
  upload: static/.*

- url: /signup
  script: signup.py
  
- url: /listsignups
  script: signup.py